/**
 * Assign Office Page
 *
 * Allows an administrator to create a new active office allocation.
 *
 * Business rules currently implemented:
 * 1. A faculty member with an active allocation is not shown.
 * 2. An office with an active allocation is not shown.
 * 3. An allocation is active when endedAt === null.
 *
 * These filters prevent normal use of this page from assigning:
 * - Multiple active offices to one faculty member.
 * - One occupied office to multiple faculty members.
 *
 * Future work:
 * The recommendation system will rank the available offices using
 * faculty rank/tenure, department building, window preference,
 * and OFFICE vs. CUBICLE.
 */

import { db } from "@/prisma/db";
import { redirect } from "next/navigation";

export default async function AddAllocationPage() {
  // Load all data needed to determine which faculty and offices
  // are currently available for a new assignment.
  const faculty = await db.orm.public.Faculty.all();
  const offices = await db.orm.public.Office.all();
  const allocations = await db.orm.public.Allocation.all();

  // An Allocation remains active until endedAt receives a timestamp.
  const activeAllocations = allocations.filter(
    (allocation) => allocation.endedAt === null
  );

  // Remove faculty who already have an active office assignment.
  const availableFaculty = faculty.filter(
    (member) =>
      !activeAllocations.some(
        (allocation) => allocation.facultyId === member.id
      )
  );

  // Remove offices that already belong to an active allocation.
  const availableOffices = offices.filter(
    (office) =>
      !activeAllocations.some(
        (allocation) => allocation.officeId === office.id
      )
  );

  async function assignOffice(formData: FormData) {
    "use server";

    const facultyId = Number(formData.get("facultyId"));
    const officeId = Number(formData.get("officeId"));

    // Creating an Allocation connects one faculty member to one office.
    // assignedAt is automatically generated by the database.
    // endedAt starts as null, making this an active allocation.
    await db.orm.public.Allocation.create({
      facultyId,
      officeId,
    });

    redirect("/admin");
  }

  return (
    <main className="p-8">
      <h1 className="text-3xl font-bold">Assign Office</h1>

      <form
        action={assignOffice}
        className="mt-8 flex max-w-md flex-col gap-4"
      >
        {/* Only faculty without an active allocation appear here. */}
        <select
          name="facultyId"
          required
          defaultValue=""
          className="border p-2"
        >
          <option value="" disabled>
            Select Faculty Member
          </option>

          {availableFaculty.map((member) => (
            <option key={member.id} value={member.id}>
              {member.firstName} {member.lastName}
            </option>
          ))}
        </select>

        {/* Only currently unoccupied offices appear here. */}
        <select
          name="officeId"
          required
          defaultValue=""
          className="border p-2"
        >
          <option value="" disabled>
            Select Office
          </option>

          {availableOffices.map((office) => (
            <option key={office.id} value={office.id}>
              {office.building} {office.roomNumber}
            </option>
          ))}
        </select>

        <button
          type="submit"
          className="border p-2 font-semibold"
        >
          Assign Office
        </button>
      </form>
    </main>
  );
}