// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'7bfbc90e129d77d3c3c7ca887a514510f84e9bd05a525bb0facaf5f7710da86a'>;
export type ExecutionHash =
  ExecutionHashBase<'054547d13912f9cb5169884a5ef924eff3721ee50204c77a3159842081d3d269'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Allocation: {
      readonly assignedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly endedAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly facultyId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly officeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Department: {
      readonly building: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Faculty: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly departmentId: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly facultyRank:
        | 'FULL'
        | 'ASSOCIATE'
        | 'ASSISTANT'
        | 'INSTRUCTIONAL_FULL'
        | 'INSTRUCTIONAL_ASSOCIATE'
        | 'INSTRUCTIONAL_ASSISTANT'
        | 'SENIOR_LECTURER'
        | 'LECTURER_INSTRUCTOR'
        | 'VISITING_INSTRUCTIONAL_ASSISTANT'
        | 'VISITING_LECTURER';
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly otherNotes: CodecTypes['pg/text@1']['output'] | null;
      readonly tenureStatus: 'TENURED' | 'TENURE_TRACK' | 'FIXED_TERM';
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Office: {
      readonly building: CodecTypes['pg/text@1']['output'];
      readonly floor: CodecTypes['pg/int4@1']['output'];
      readonly hasWindow: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly roomNumber: CodecTypes['pg/text@1']['output'];
      readonly spaceType: 'OFFICE' | 'CUBICLE';
      readonly status: 'AVAILABLE' | 'RESERVED' | 'UNAVAILABLE';
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Allocation: {
      readonly assignedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly endedAt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly facultyId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly officeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Department: {
      readonly building: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Faculty: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly departmentId: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly facultyRank:
        | 'FULL'
        | 'ASSOCIATE'
        | 'ASSISTANT'
        | 'INSTRUCTIONAL_FULL'
        | 'INSTRUCTIONAL_ASSOCIATE'
        | 'INSTRUCTIONAL_ASSISTANT'
        | 'SENIOR_LECTURER'
        | 'LECTURER_INSTRUCTOR'
        | 'VISITING_INSTRUCTIONAL_ASSISTANT'
        | 'VISITING_LECTURER';
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly otherNotes: CodecTypes['pg/text@1']['input'] | null;
      readonly tenureStatus: 'TENURED' | 'TENURE_TRACK' | 'FIXED_TERM';
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Office: {
      readonly building: CodecTypes['pg/text@1']['input'];
      readonly floor: CodecTypes['pg/int4@1']['input'];
      readonly hasWindow: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly roomNumber: CodecTypes['pg/text@1']['input'];
      readonly spaceType: 'OFFICE' | 'CUBICLE';
      readonly status: 'AVAILABLE' | 'RESERVED' | 'UNAVAILABLE';
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Allocation: {
      readonly assignedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly endedAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly facultyId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly officeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Department: {
      readonly building: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Faculty: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly departmentId: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly facultyRank:
        | 'FULL'
        | 'ASSOCIATE'
        | 'ASSISTANT'
        | 'INSTRUCTIONAL_FULL'
        | 'INSTRUCTIONAL_ASSOCIATE'
        | 'INSTRUCTIONAL_ASSISTANT'
        | 'SENIOR_LECTURER'
        | 'LECTURER_INSTRUCTOR'
        | 'VISITING_INSTRUCTIONAL_ASSISTANT'
        | 'VISITING_LECTURER';
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'];
      readonly otherNotes: CodecTypes['pg/text@1']['output'] | null;
      readonly tenureStatus: 'TENURED' | 'TENURE_TRACK' | 'FIXED_TERM';
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Office: {
      readonly building: CodecTypes['pg/text@1']['output'];
      readonly floor: CodecTypes['pg/int4@1']['output'];
      readonly hasWindow: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly roomNumber: CodecTypes['pg/text@1']['output'];
      readonly spaceType: 'OFFICE' | 'CUBICLE';
      readonly status: 'AVAILABLE' | 'RESERVED' | 'UNAVAILABLE';
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Allocation: {
      readonly assignedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly endedAt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly facultyId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly officeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Department: {
      readonly building: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Faculty: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly departmentId: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly facultyRank:
        | 'FULL'
        | 'ASSOCIATE'
        | 'ASSISTANT'
        | 'INSTRUCTIONAL_FULL'
        | 'INSTRUCTIONAL_ASSOCIATE'
        | 'INSTRUCTIONAL_ASSISTANT'
        | 'SENIOR_LECTURER'
        | 'LECTURER_INSTRUCTOR'
        | 'VISITING_INSTRUCTIONAL_ASSISTANT'
        | 'VISITING_LECTURER';
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'];
      readonly otherNotes: CodecTypes['pg/text@1']['input'] | null;
      readonly tenureStatus: 'TENURED' | 'TENURE_TRACK' | 'FIXED_TERM';
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Office: {
      readonly building: CodecTypes['pg/text@1']['input'];
      readonly floor: CodecTypes['pg/int4@1']['input'];
      readonly hasWindow: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly roomNumber: CodecTypes['pg/text@1']['input'];
      readonly spaceType: 'OFFICE' | 'CUBICLE';
      readonly status: 'AVAILABLE' | 'RESERVED' | 'UNAVAILABLE';
    };
  };
};

export namespace Models {
  export type public_Allocation = {
    assignedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    endedAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    facultyId: CodecTypes['pg/int4@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    officeId: CodecTypes['pg/int4@1']['output'];
    faculty: public_Faculty;
    office: public_Office;
    readonly [RelationKeys]?: 'faculty' | 'office';
  };
  export type public_Department = {
    building: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    facultyMembers: public_Faculty[];
    readonly [RelationKeys]?: 'facultyMembers';
  };
  export type public_Faculty = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    departmentId: CodecTypes['pg/int4@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    facultyRank:
      | 'FULL'
      | 'ASSOCIATE'
      | 'ASSISTANT'
      | 'INSTRUCTIONAL_FULL'
      | 'INSTRUCTIONAL_ASSOCIATE'
      | 'INSTRUCTIONAL_ASSISTANT'
      | 'SENIOR_LECTURER'
      | 'LECTURER_INSTRUCTOR'
      | 'VISITING_INSTRUCTIONAL_ASSISTANT'
      | 'VISITING_LECTURER';
    firstName: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    lastName: CodecTypes['pg/text@1']['output'];
    otherNotes: CodecTypes['pg/text@1']['output'] | null;
    tenureStatus: 'TENURED' | 'TENURE_TRACK' | 'FIXED_TERM';
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    allocations: public_Allocation[];
    department: public_Department;
    readonly [RelationKeys]?: 'allocations' | 'department';
  };
  export type public_Office = {
    building: CodecTypes['pg/text@1']['output'];
    floor: CodecTypes['pg/int4@1']['output'];
    hasWindow: CodecTypes['pg/bool@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    roomNumber: CodecTypes['pg/text@1']['output'];
    spaceType: 'OFFICE' | 'CUBICLE';
    status: 'AVAILABLE' | 'RESERVED' | 'UNAVAILABLE';
    allocations: public_Allocation[];
    readonly [RelationKeys]?: 'allocations';
  };
}

export declare const models: {
  public: {
    Allocation: Models.public_Allocation;
    Department: Models.public_Department;
    Faculty: Models.public_Faculty;
    Office: Models.public_Office;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Allocation: {
              columns: {
                readonly assignedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly endedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly facultyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly officeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Allocation';
                    readonly columns: readonly ['facultyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Faculty';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Allocation';
                    readonly columns: readonly ['officeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Office';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Department: {
              columns: {
                readonly building: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Department_name_key';
                  readonly columns: readonly ['name'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly Faculty: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly departmentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly facultyRank: {
                  readonly nativeType: 'FacultyRank';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'FacultyRank' };
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly lastName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly otherNotes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tenureStatus: {
                  readonly nativeType: 'TenureStatus';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'TenureStatus' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Faculty_email_key';
                  readonly columns: readonly ['email'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Faculty';
                    readonly columns: readonly ['departmentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Department';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Office: {
              columns: {
                readonly building: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly floor: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly hasWindow: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly roomNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly spaceType: {
                  readonly nativeType: 'SpaceType';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'SpaceType' };
                };
                readonly status: {
                  readonly nativeType: 'OfficeStatus';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'AVAILABLE'>;
                  };
                  readonly typeParams: { readonly typeName: 'OfficeStatus' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly FacultyRank: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'FULL',
                'ASSOCIATE',
                'ASSISTANT',
                'INSTRUCTIONAL_FULL',
                'INSTRUCTIONAL_ASSOCIATE',
                'INSTRUCTIONAL_ASSISTANT',
                'SENIOR_LECTURER',
                'LECTURER_INSTRUCTOR',
                'VISITING_INSTRUCTIONAL_ASSISTANT',
                'VISITING_LECTURER',
              ];
            };
            readonly OfficeStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['AVAILABLE', 'RESERVED', 'UNAVAILABLE'];
            };
            readonly SpaceType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['OFFICE', 'CUBICLE'];
            };
            readonly TenureStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['TENURED', 'TENURE_TRACK', 'FIXED_TERM'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Allocation: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Allocation';
    };
    readonly Department: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Department';
    };
    readonly Faculty: { readonly namespace: 'public' & NamespaceId; readonly model: 'Faculty' };
    readonly Office: { readonly namespace: 'public' & NamespaceId; readonly model: 'Office' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Allocation: {
            readonly fields: {
              readonly assignedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly endedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly facultyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly officeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly faculty: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Faculty';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['facultyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly office: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Office';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['officeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Allocation';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly assignedAt: { readonly column: 'assignedAt' };
                readonly endedAt: { readonly column: 'endedAt' };
                readonly facultyId: { readonly column: 'facultyId' };
                readonly id: { readonly column: 'id' };
                readonly officeId: { readonly column: 'officeId' };
              };
            };
          };
          readonly Department: {
            readonly fields: {
              readonly building: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly facultyMembers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Faculty';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['departmentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Department';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly building: { readonly column: 'building' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Faculty: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly departmentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly facultyRank: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'FacultyRank' };
                };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly lastName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly otherNotes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tenureStatus: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'TenureStatus' };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly allocations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Allocation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['facultyId'];
                };
              };
              readonly department: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Department';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['departmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Faculty';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly departmentId: { readonly column: 'departmentId' };
                readonly email: { readonly column: 'email' };
                readonly facultyRank: { readonly column: 'facultyRank' };
                readonly firstName: { readonly column: 'firstName' };
                readonly id: { readonly column: 'id' };
                readonly lastName: { readonly column: 'lastName' };
                readonly otherNotes: { readonly column: 'otherNotes' };
                readonly tenureStatus: { readonly column: 'tenureStatus' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Office: {
            readonly fields: {
              readonly building: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly floor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly hasWindow: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly roomNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly spaceType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'SpaceType' };
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'OfficeStatus' };
                };
              };
            };
            readonly relations: {
              readonly allocations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Allocation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['officeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Office';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly building: { readonly column: 'building' };
                readonly floor: { readonly column: 'floor' };
                readonly hasWindow: { readonly column: 'hasWindow' };
                readonly id: { readonly column: 'id' };
                readonly roomNumber: { readonly column: 'roomNumber' };
                readonly spaceType: { readonly column: 'spaceType' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'plainDateTimeNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Faculty';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
